# Generated by Django 5.0.6 on 2024-07-20 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anacad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denom_anacad', models.CharField(blank=True, max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dom', models.CharField(blank=True, max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elenent_Const',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denom_ue', models.CharField(max_length=70)),
                ('niveau_ue', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='MaListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fac', models.CharField(blank=True, max_length=70, unique=True)),
                ('id_dom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.domaine')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fil', models.CharField(blank=True, max_length=70, unique=True)),
                ('id_fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.faculte')),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mention', models.CharField(blank=True, max_length=70, unique=True)),
                ('id_fil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Partie_ec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partie_ec_choice', models.CharField(choices=[('tp', 'Travail Pratique'), ('cmi', 'Cours magistral')], max_length=68)),
                ('id_anacad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.anacad')),
                ('id_ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.elenent_const')),
            ],
        ),
        migrations.CreateModel(
            name='Programme_ec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('id_partie_ec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.partie_ec')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prom', models.CharField(blank=True, max_length=70, unique=True)),
                ('id_mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.mention')),
            ],
        ),
        migrations.CreateModel(
            name='Unite_Ens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_ue', models.CharField(blank=True, max_length=10, unique=True)),
                ('denom_ue', models.CharField(blank=True, max_length=70)),
                ('semstre', models.CharField(choices=[('premier', 'Premier Semestre'), ('second', 'Second Semestre')], max_length=7)),
                ('id_promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.promotion')),
            ],
        ),
        migrations.AddField(
            model_name='elenent_const',
            name='id_ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.unite_ens'),
        ),
    ]
