# Generated by Django 5.0.6 on 2024-07-20 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('horaire_univ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie_ec',
            name='id_enseignant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.enseignant'),
        ),
        migrations.AlterUniqueTogether(
            name='partie_ec',
            unique_together={('id_ec', 'partie_ec_choice', 'id_anacad')},
        ),
    ]
