# Generated by Django 5.0.6 on 2024-07-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horaire_univ', '0002_partie_ec_id_enseignant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elenent_const',
            old_name='denom_ue',
            new_name='denom_ec',
        ),
        migrations.RenameField(
            model_name='elenent_const',
            old_name='niveau_ue',
            new_name='niveau_ec',
        ),
    ]
