# Generated by Django 5.0.6 on 2024-07-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaire_univ', '0003_rename_denom_ue_elenent_const_denom_ec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie_ec',
            name='volume_horaire',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
