# Generated by Django 5.0.6 on 2024-08-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaire_univ', '0004_partie_ec_volume_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='nom_prom',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
