# Generated by Django 5.0.6 on 2024-08-27 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horaire_univ', '0005_alter_promotion_nom_prom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme_ec',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='programme_ec',
            name='date_fin',
        ),
        migrations.AddField(
            model_name='partie_ec',
            name='date_debut',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partie_ec',
            name='date_fin',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
