# Generated by Django 5.0.6 on 2024-07-20 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horaire_univ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste_jours', models.TextField()),
                ('id_partie_ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.partie_ec')),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('partie_journ', models.CharField(choices=[('matin', 'Matin'), ('soir', 'Soir')], max_length=5)),
                ('id_partie_ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.partie_ec')),
            ],
            options={
                'unique_together': {('date', 'partie_journ')},
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senestre_period', models.CharField(choices=[('premier', 'Premier Semestre'), ('second', 'Second Semestre')], max_length=7)),
                ('date_debut_semestre', models.DateField()),
                ('date_fin_semestre', models.DateField()),
                ('anacad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.anacad')),
            ],
            options={
                'unique_together': {('anacad', 'senestre_period')},
            },
        ),
    ]
