# Generated by Django 5.0.6 on 2024-07-20 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('dispo_app', '0001_initial'),
        ('horaire_univ', '0002_partie_ec_id_enseignant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilite',
            name='id_enseignant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.enseignant'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilite',
            unique_together={('id_enseignant', 'id_partie_ec')},
        ),
    ]
