# Generated by Django 5.0.6 on 2024-07-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispo_app', '0002_disponibilite_id_enseignant_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disponibilite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='disponibilite',
            name='id_enseignant',
        ),
    ]
