# Generated by Django 5.0.6 on 2024-10-14 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispo_app', '0003_alter_disponibilite_unique_together_and_more'),
        ('horaire_univ', '0007_remove_programme_ec_id_partie_ec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilite',
            name='id_partie_ec',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.partie_ec'),
        ),
    ]
