# Generated by Django 5.0.6 on 2024-08-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='statut',
            field=models.CharField(choices=[('permanent', 'Permanant'), ('visiteur', 'Visiteur')], default='permanant', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='niveau_ens',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
