# Generated by Django 5.0.6 on 2024-07-16 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('horaire_univ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef_promotion',
            name='id_anacad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.anacad'),
        ),
        migrations.AddField(
            model_name='chef_promotion',
            name='id_promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.promotion'),
        ),
        migrations.AddField(
            model_name='encadreur_faculte',
            name='id_anacad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.anacad'),
        ),
        migrations.AddField(
            model_name='encadreur_faculte',
            name='id_faculte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaire_univ.faculte'),
        ),
        migrations.AddField(
            model_name='encadreur_faculte',
            name='id_ens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.enseignant'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='myuser_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='myuser_set', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.myuser'),
        ),
        migrations.AddField(
            model_name='chef_promotion',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.myuser'),
        ),
        migrations.AlterUniqueTogether(
            name='encadreur_faculte',
            unique_together={('id_faculte', 'id_anacad')},
        ),
    ]
