# Generated by Django 5.0.6 on 2024-09-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_enseignant_statut_alter_enseignant_niveau_ens'),
        ('horaire_univ', '0007_remove_programme_ec_id_partie_ec_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='encadreur_faculte',
            unique_together={('id_ens', 'id_anacad'), ('id_faculte', 'id_anacad')},
        ),
    ]
